import { randomUUID, randomInt } from "node:crypto";

const fields = "id,user_id,meal_id,title,image_url";
export const checkNames = [
  "B skaito A bandomąjį įrašą pagal UUID",
  "B trina A bandomąjį įrašą pagal UUID",
  "B įterpia bandomąjį įrašą su A user_id",
  "Anoniminis vartotojas skaito saved_recipes",
  "A bandomasis įrašas išlieka nepakitęs",
];

export async function checkAnonymous(anon) {
  // limit(0) probes table permissions without retrieving anyone's data.
  const response = await anon.from("saved_recipes").select("id").limit(0);
  if ([401, 403].includes(response.status) && response.error?.code === "42501") {
    return { status: "PASS", detail: "Prieiga atmesta: 42501 (duomenų bazės leidimai)." };
  }
  return { status: response.error ? "INCONCLUSIVE" : "FAIL", detail: response.error ? "Nepavyko patvirtinti laukiamo prieigos draudimo." : "Anoniminė SELECT užklausa nebuvo atmesta leidimų lygmeniu." };
}

export async function runRlsChecks({ a, b, anon, aId, bId, report = () => {} }) {
  if (!aId || !bId || aId === bId) throw new Error("Reikalingi du skirtingi patikrinti vartotojai.");
  const marker = `Fridge Rescue RLS TEST ${randomUUID()}`;
  const fixture = owner => ({ id: randomUUID(), user_id: owner, meal_id: String(randomInt(100000000, 999999999)), title: marker, image_url: "https://example.invalid/rls-test.png" });
  const aRow = fixture(aId);
  const bRow = fixture(bId);
  const forgedRow = fixture(aId);
  const fixtures = [aRow, bRow, forgedRow];
  const results = [];
  const emit = (index, status, detail) => { const result = { test: index + 1, name: checkNames[index], status, detail }; results.push(result); report(result); };
  const read = (client, row) => client.from("saved_recipes").select(fields).eq("id", row.id);
  let cleanup = "PASS";
  try {
    // Positive controls prevent "RLS passed" when B simply has no working access at all.
    for (const [client, row] of [[a, aRow], [b, bRow]]) {
      const inserted = await client.from("saved_recipes").insert(row);
      if (inserted.error) throw new Error("Kontrolinis savo įrašo INSERT nepavyko.");
      const own = await read(client, row);
      if (own.error || own.data?.length !== 1) throw new Error("Kontrolinis savo įrašo SELECT nepavyko.");
    }
    const ownDelete = await b.from("saved_recipes").delete().eq("id", bRow.id).select("id");
    if (ownDelete.error || ownDelete.data?.length !== 1) throw new Error("Kontrolinis savo įrašo DELETE nepavyko.");

    // Deliberately no user_id filter: these calls test database enforcement, not app filters.
    const foreignRead = await read(b, aRow);
    emit(0, foreignRead.error ? "INCONCLUSIVE" : foreignRead.data?.length === 0 ? "PASS" : "FAIL",
      foreignRead.error ? "SELECT klaida; vien klaida neįrodo RLS veikimo." : foreignRead.data?.length === 0 ? "B gavo tuščią sąrašą." : "B galėjo perskaityti svetimą bandomąjį įrašą.");

    const foreignDelete = await b.from("saved_recipes").delete().eq("id", aRow.id).select("id");
    const afterDelete = await read(a, aRow);
    const stillExists = !afterDelete.error && afterDelete.data?.length === 1;
    emit(1, foreignDelete.error || afterDelete.error ? "INCONCLUSIVE" : foreignDelete.data?.length === 0 && stillExists ? "PASS" : "FAIL",
      foreignDelete.error || afterDelete.error ? "Nepavyko patikimai patikrinti DELETE rezultato." : stillExists && foreignDelete.data?.length === 0 ? "B nepašalino nė vienos eilutės; A įrašas išliko." : "A bandomojo įrašo apsauga nesuveikė.");

    const forged = await b.from("saved_recipes").insert(forgedRow);
    const forgedExists = await read(a, forgedRow);
    emit(2, forgedExists.error ? "INCONCLUSIVE" : forged.error?.code === "42501" && forgedExists.data?.length === 0 ? "PASS" : !forged.error || forgedExists.data?.length ? "FAIL" : "INCONCLUSIVE",
      forged.error?.code === "42501" && !forgedExists.error && forgedExists.data?.length === 0 ? "INSERT atmestas su 42501; įrašas nesukurtas." : "Laukiamas svetimo savininko INSERT draudimas nepatvirtintas.");

    const anonymous = await checkAnonymous(anon);
    emit(3, anonymous.status, anonymous.detail);

    const final = await read(a, aRow);
    const intact = !final.error && final.data?.length === 1 && Object.entries(aRow).every(([key, value]) => final.data[0][key] === value);
    emit(4, final.error ? "INCONCLUSIVE" : intact ? "PASS" : "FAIL", final.error ? "Nepavyko perskaityti kontrolinio įrašo." : intact ? "A bandomasis įrašas nepakitęs (prieš testinių duomenų valymą)." : "A bandomasis įrašas neišliko nepakitęs.");
  } catch {
    for (let index = results.length; index < checkNames.length; index++) emit(index, "INCONCLUSIVE", "Testas neužbaigtas: nepavyko kontrolinė operacija arba ryšys. Rezultatas nėra PASS.");
  } finally {
    // Only IDs generated by this run, additionally guarded by owner and unique marker.
    // Existing user recipes are never used as DELETE targets, even if RLS is broken.
    for (const row of fixtures) {
      const client = row.user_id === aId ? a : b;
      try {
        const removed = await client.from("saved_recipes").delete().eq("id", row.id).eq("user_id", row.user_id).eq("title", marker);
        const remaining = await read(client, row);
        if (removed.error || remaining.error || remaining.data?.length) cleanup = "INCONCLUSIVE";
      } catch { cleanup = "INCONCLUSIVE"; }
    }
    report({ name: "Tik šio paleidimo bandomųjų duomenų valymas", status: cleanup, detail: cleanup === "PASS" ? "Patikrinta: bandomųjų įrašų neliko." : "Patikrinkite lentelėje įrašus su pavadinimu Fridge Rescue RLS TEST. Esamų receptų netrinkite." });
  }
  return { results, cleanup };
}
